name = "UM永不妥协UMSS奇遇控制"
author = "codex"
version = "1.1.2"
forumthread = ""
api_version = 10
dst_compatible = true
all_clients_require_mod = false
client_only_mod = false
server_only_mod = true
server_filter_tags = { "um", "uncompromising", "umss" }
icon_atlas = ""
icon = ""

description = [[服务器端补丁，用来控制永不妥协 UM 自己的 UMSS 奇遇。

这些代码来自永不妥协 scripts/umss_tables.lua，控制台 c_um_umss("代码") 也是按这里的 name 查找。UMSS 不是原版世界设置里的 boons；把原版“奇遇”设为 never 不能阻止这些 UMSS setpiece。

配置里可以一键拦截全部 UMSS，也可以逐项选择。默认只拦截 moonFrag，其他保持允许。]]

configuration_options =
{
    {
        name = "block_mode",
        label = "UMSS 拦截模式",
        hover = "指定列表=只按下面列表拦截；全部 UMSS=所有 umss_tables.lua 里的 UMSS 都不生成；关闭补丁=不拦截。",
        options =
        {
            { description = "指定列表", data = "selected", hover = "只拦截下面设置为“拦截”的 UMSS。" },
            { description = "全部 UMSS", data = "all_umss", hover = "所有 UMSS 奇遇都会被阻止，包括世界生成和 c_um_umss 手动调出。" },
            { description = "关闭补丁", data = "off", hover = "不拦截任何 UMSS。" },
        },
        default = "selected",
    },
    {
        name = "block_umss_baseFrag_rattyStorage",
        label = "储物间残片",
        hover = "储物间残片：木墙、多个箱子、衣柜和 uncompromising_rat。源码代码：baseFrag_rattyStorage",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_singlefather",
        label = "小营地骨架",
        hover = "小营地骨架：腐烂食物、恐怖之眼小随从、烂巨型榴莲、火坑和骷髅。源码代码：singlefather",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_megabaseruins_road",
        label = "远古遗迹路段",
        hover = "远古遗迹路段：大量 umdc_tileflag 铺出的道路，加少量种子。源码代码：megabaseruins_road",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_moonOil",
        label = "月油浆果点",
        hover = "月油浆果点：浆果丛、diseasecurebomb、骷髅。源码代码：moonOil",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_failedFisherman",
        label = "失败渔夫",
        hover = "失败渔夫：船、锚、鱼箱、桅杆、钓具和腐烂鱼。源码代码：failedFisherman",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_testTable",
        label = "测试表",
        hover = "测试表：科学机器和草。源码代码：testTable",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_testTable2",
        label = "测试表 2",
        hover = "测试表 2：常青树和猪屋。源码代码：testTable2",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_dudu_DUN_DUN",
        label = "月亮药水小彩蛋",
        hover = "小彩蛋：月亮万圣药水和骷髅。源码代码：dudu DUN DUN",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_Guardian_Of_Nothing",
        label = "守护者废墟",
        hover = "守护者废墟：石墙、月岩墙、月岩、遗迹/马赛克地皮。源码代码：Guardian Of Nothing",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_fooltrap1Table",
        label = "气球芦苇陷阱",
        hover = "气球芦苇陷阱：大量气球、触手、芦苇和骷髅。源码代码：fooltrap1Table",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_testTable4",
        label = "测试表 4",
        hover = "测试表 4：树林、木墙/栅栏、箱子、斧头和火把。源码代码：testTable4",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_inactivebiome_test",
        label = "海上非活跃生态测试",
        hover = "海上非活跃生态测试：海蚀柱、淤泥堆和 searock_ring。源码代码：inactivebiome_test",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_moxTable",
        label = "Mox 小彩蛋",
        hover = "Mox 小彩蛋：兔肉炖锅、兔人尾巴和高礼帽。源码代码：moxTable",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_grassTrap",
        label = "草陷阱",
        hover = "草陷阱：大量 trapdoorspawner 混在草丛里。源码代码：grassTrap",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_scorpionOutskirts1",
        label = "蝎子外围 1",
        hover = "蝎子外围 1：蝎子洞、沙丘、沙岩、虫婴岩。源码代码：scorpionOutskirts1",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_scorpionOutskirts2",
        label = "蝎子外围 2",
        hover = "蝎子外围 2：蝎子洞、虫婴岩、沙丘和犬骨。源码代码：scorpionOutskirts2",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_scorpionOutskirts3",
        label = "蝎子外围 3",
        hover = "蝎子外围 3：蝎子洞、沙岩和尖刺灌木。源码代码：scorpionOutskirts3",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_scorpionOutskirts4",
        label = "蝎子外围 4",
        hover = "蝎子外围 4：沙岩、虫婴岩和蝎子洞。源码代码：scorpionOutskirts4",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_activebiome_cbts_ss",
        label = "海上活跃生态 SS",
        hover = "海上活跃生态 SS：海蚀柱、船残骸、kelpstack、幽灵沉船、siren_throne。源码代码：activebiome_cbts_ss",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_activebiome_cbts_bb",
        label = "海上活跃生态 BB",
        hover = "海上活跃生态 BB：牛海带、mossstack、海树、盐堆、siren_bird_nest。源码代码：activebiome_cbts_bb",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_activebiome_test_bb",
        label = "活跃生态测试 BB",
        hover = "海上活跃生态测试 BB：海蚀柱、淤泥堆和 siren_bird_nest。源码代码：activebiome_test_bb",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_activebiome_test_rr",
        label = "活跃生态测试 RR",
        hover = "海上活跃生态测试 RR：海蚀柱、淤泥堆和 ocean_speaker。源码代码：activebiome_test_rr",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_activebiome_test_ss",
        label = "活跃生态测试 SS",
        hover = "海上活跃生态测试 SS：海蚀柱、淤泥堆和 siren_throne。源码代码：activebiome_test_ss",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_LazyBase",
        label = "懒人基地",
        hover = "懒人基地：地皮旗、栅栏、木墙、蜂箱、花和猪王火炬。源码代码：LazyBase",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_swamplake",
        label = "沼泽湖",
        hover = "沼泽湖：大片 umdc_tileflag、水稻、海藤、船和少量海上资源。源码代码：swamplake",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_B_MonkeyOutpost",
        label = "猴子哨站 B",
        hover = "猴子哨站 B：草地哨站、猴屋、宝箱、海盗旗、炮和海盗船。源码代码：B_MonkeyOutpost",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_megabaseruins_centerpiece",
        label = "远古遗迹中心",
        hover = "远古遗迹中心：大量 umdc_tileflag 组成的中心结构。源码代码：megabaseruins_centerpiece",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_funFair",
        label = "游乐场小彩蛋",
        hover = "游乐场小彩蛋：voorhams。源码代码：funFair",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_startPortal",
        label = "出生门变体",
        hover = "出生门变体：传送门、花、草、种子、蝴蝶和 trapdoor/trapdoorgrass。源码代码：startPortal",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_funniPortal",
        label = "简化出生门变体",
        hover = "简化出生门变体：传送门和少量花。源码代码：funniPortal",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_ancientwalrusTable",
        label = "远古海象陷阱",
        hover = "远古海象陷阱：旧熊夹、吹箭、夏威夷衬衫、种子和腐烂食物。源码代码：ancientwalrusTable",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_baseFrag_smellyKitchen",
        label = "臭厨房残片",
        hover = "臭厨房残片：腐烂食物、蕨类盆栽、锅、冰箱和晾肉架。源码代码：baseFrag_smellyKitchen",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_returnedTable273",
        label = "空表 / 占位",
        hover = "源码表为空：可能是占位或废弃 UMSS。源码代码：returnedTable273",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_wixie_puzzle",
        label = "Wixie 谜题",
        hover = "Wixie 谜题：wixie_piano、charles_t_horse、wixie_wardrobe、wixie_clock。源码代码：wixie_puzzle",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_megabaseruins_intersection",
        label = "远古遗迹十字路口",
        hover = "远古遗迹十字路口：大量 umdc_tileflag 和石墙。源码代码：megabaseruins_intersection",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_MAGMASPLOTCH1",
        label = "岩浆地皮点 1",
        hover = "岩浆地皮点 1：单个岩浆地皮旗。源码代码：MAGMASPLOTCH1",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_MAGMASPLOTCH2",
        label = "岩浆地皮点 2",
        hover = "岩浆地皮点 2：两个岩浆地皮旗。源码代码：MAGMASPLOTCH2",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_MAGMASPLOTCH3",
        label = "岩浆地皮点 3",
        hover = "岩浆地皮点 3：三个岩浆地皮旗。源码代码：MAGMASPLOTCH3",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_MAGMASPLOTCH4",
        label = "岩浆地皮点 4",
        hover = "岩浆地皮点 4：五个岩浆地皮旗。源码代码：MAGMASPLOTCH4",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_testTable3",
        label = "测试表 3",
        hover = "测试表 3：浮木和 dock_kit，带海岸/码头地皮旗。源码代码：testTable3",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_sos",
        label = "SOS 标记",
        hover = "SOS 标记：大量地皮旗、信号弹、火把和骷髅。源码代码：sos",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_inactivebiome_cbts_3",
        label = "海上非活跃生态 3",
        hover = "海上非活跃生态 3：海树、海藤、树根、藤壶茧和水中树干。源码代码：inactivebiome_cbts_3",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_inactivebiome_cbts_1",
        label = "海上非活跃生态 1",
        hover = "海上非活跃生态 1：水草和淤泥堆。源码代码：inactivebiome_cbts_1",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_inactivebiome_cbts_2",
        label = "海上非活跃生态 2",
        hover = "海上非活跃生态 2：盐堆和饼干切割机刷新点。源码代码：inactivebiome_cbts_2",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_walterifgood",
        label = "Walter 小营地",
        hover = "Walter 小营地：常青树、骷髅、毛皮/草席卷、火坑和蜘蛛巢。源码代码：walterifgood",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_scorpionCenter1",
        label = "蝎子中心",
        hover = "蝎子中心：大量沙岩/沙丘/蝎子洞，含 um_scorpion。源码代码：scorpionCenter1",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_badfarmerTable",
        label = "坏农夫",
        hover = "坏农夫：旧农场、锄头、熟种子和骷髅。源码代码：badfarmerTable",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_demoTable",
        label = "演示表",
        hover = "演示表：大量木头、海蚀柱和 splash。源码代码：demoTable",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_sunkenboat",
        label = "沉船残骸",
        hover = "沉船残骸：船碎片、绳子、蛛丝、骨片、木炭和浮木。源码代码：sunkenboat",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_moonFrag",
        label = "月岛碎片",
        hover = "月岛碎片：月玻璃岩、月树、落叶树、草、树苗、石果灌木等。默认拦截。源码代码：moonFrag",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = true,
    },
    {
        name = "block_umss_sussyTable",
        label = "可疑地皮图案",
        hover = "可疑地皮图案：大量 umdc_tileflag 和犬骨。源码代码：sussyTable",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_tridentTrap",
        label = "三叉戟陷阱",
        hover = "三叉戟陷阱：水草、海蚀柱、船、海带帽、骷髅和三叉戟。源码代码：tridentTrap",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_A_MonkeyOutpost",
        label = "猴子哨站 A",
        hover = "猴子哨站 A：大型猴屋/码头/海盗旗/炮结构，带沼泽和水稻边缘。源码代码：A_MonkeyOutpost",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
    {
        name = "block_umss_impactfulDiscovery",
        label = "撞击发现",
        hover = "撞击发现：木墙残骸、岩石、木炭、石砖、树枝、草甲和月岩。源码代码：impactfulDiscovery",
        options = { { description = "拦截", data = true }, { description = "允许", data = false } },
        default = false,
    },
}
